package com.demo.exception;

import java.io.FileNotFoundException;
import java.io.IOException;

public class ExceptionHandlingDemo {
 int id;
	
	
	public static void main(String[] args) throws FileNotFoundException  {
		// TODO Auto-generated method stub
		
		//checked exception
		/*try {
			
			
		BackendApplication.send(1, "", "http://abc.test.com");
		}catch (FileNotFoundException e) {
		
			System.out.println("inside main: catch block");
			throw e;
		}catch (IOException e) {
			// TODO Auto-generated catch block
		//	e.printStackTrace();
			
		}
		
		
	System.out.println("In main : after exception");*/
		
		
		
		//unchecked exception 1
		
		int[] myArr =  {1,2,3};
		System.out.println("my array:"+myArr[4]);
		
		//unchecked exception
		
		
		
	}
		
		
		
		
		

}
